data:
    name: timit
    batch_size: 2
    win_size: 400
    hop_size: 160
    sample_rate: 16000
    n_mfcc: 13
    num_mel_bins: 23
    center: False
    separator: '_'
model:
    enc:
        type: lstm
        hidden_size: 320
        output_size: 320
        n_layers: 4
        bidirectional: True
        dropout: 0.0
    dec:
        type: lstm
        hidden_size: 512
        output_size: 320
        n_layers: 2
        dropout: 0.0
    joint:
        input_size: 640
        inner_size: 512

    vocab_size: 31
    share_weight: False
    feature_dim: 13
    blank: 27
    max_length: 100
    device: 'cuda'
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 42
    num_gpu: 1
    epochs: 2000
    max_grad_norm: 40
    visualization: True
    show_interval: 2
    save_model: rnnt
    save_every: 30
optim:
    type: adam
    lr: 0.002
    momentum: 0.9
    decay_ratio: 0.8
    weight_decay: 0
    begin_to_adjust_lr: 40
    adjust_every: 20
    nesterov: True 